spring.application.name=toy-store-backend

#server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:mysql://localhost:3306/toy-store-db
spring.datasource.username=root
spring.datasource.password=@cpp2510

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

